### PR TITLE
Add Dependabot configuration

### PR DESCRIPTION
**Pull request by WadeBarnes**
- Configure Dependabot to automatically maintain dependencies for GitHub Actions.
  - Check for updates once a week.
  - Group all updates into a single PR.

### CODE REVIEW

**Review by swcurran — APPROVED** [review]

**Comment by WadeBarnes** [comment]
Build errors should have nothing to do with the changes in this PR.

**Comment by swcurran** [comment]
Suggestions on how to get this fixed, @WadeBarnes?  Issue added, along with another about the tests failing (perhaps related).

**Review by swcurran — APPROVED** [review]

**Comment by WadeBarnes** [comment]
Build errors addressed by https://github.com/hyperledger/indy-cli-rs/pull/13.  PR has been rebased on the changes.

**Comment by swcurran** [comment]
Any suggestions on what to do with macos-latest error?  Weird that it only happens with MacOS, as it seems to be a pretty generic error.  @Artemkaaas — would you be able to look at the error?

Obviously, this PR didn’t create the error, and the same error is occuring with other PRs.  Nice to have it cleaned up.

**Comment by WadeBarnes** [comment]
Strange that the tests ran successfully here, https://github.com/hyperledger/indy-cli-rs/actions/runs/8146791995, but not now.

**Comment by WadeBarnes** [comment]
Test are failing due to pool connection issues.

**Comment by WadeBarnes** [comment]
Seemingly a timing issue with the node pool staring up.  The tests are passing now in the latest job rerun.

**Pull request merged**
