### PR TITLE
chore: updating dependabot to support GHA, cargo and docker packages

### PR DESCRIPTION
**Pull request by rajpalc7**

### CODE REVIEW

**Comment by rajpalc7** [comment]
Hi @WadeBarnes , this is ready for review now.

**Review by WadeBarnes — APPROVED** [review]

**Review by WadeBarnes — APPROVED** [review]
LGTM, but I'll leave the final review and approval to the regular maintainers.

**Review by swcurran — APPROVED** [review]

**Comment by swcurran** [comment]
@WadeBarnes — what do you want to do about the failing test?  Looks unrelated obviously. Go ahead with the merge?

**Comment by WadeBarnes** [comment]
Yes, you can go ahead with the merge.  I added a ticket to look at the build.

**Pull request merged**
